-- View: Pitchbook.clean.companies_clean
-- Casts all numeric/timestamp fields from raw STRING ingestion,
-- strips PitchBook copyright footer rows, and deduplicates by
-- company_id keeping the most recent ingestion.

SELECT
  company_id AS company_id,
  companies AS companies,
  SAFE_CAST(last_known_valuation AS FLOAT64) AS last_known_valuation,
  SAFE_CAST(last_known_valuation_date AS TIMESTAMP) AS last_known_valuation_date,
  last_known_valuation_deal_type AS last_known_valuation_deal_type,
  SAFE_CAST(last_known_valuation_step_up AS FLOAT64) AS last_known_valuation_step_up,
  SAFE_CAST(total_raised AS FLOAT64) AS total_raised,
  active_investors AS active_investors,
  SAFE_CAST(year_founded AS FLOAT64) AS year_founded,
  website AS website,
  financing_status_note AS financing_status_note,
  SAFE_CAST(number_active_investors AS FLOAT64) AS number_active_investors,
  acquirers AS acquirers,
  former_investors AS former_investors,
  other_investors AS other_investors,
  active_investors_websites AS active_investors_websites,
  former_investors_websites AS former_investors_websites,
  other_investors_websites AS other_investors_websites,
  company_former_name AS company_former_name,
  company_also_known_as AS company_also_known_as,
  company_legal_name AS company_legal_name,
  registration_number AS registration_number,
  company_registry AS company_registry,
  competitors AS competitors,
  pbid AS pbid,
  description AS description,
  primary_industry_sector AS primary_industry_sector,
  primary_industry_group AS primary_industry_group,
  primary_industry_code AS primary_industry_code,
  all_industries AS all_industries,
  verticals AS verticals,
  keywords AS keywords,
  emerging_spaces AS emerging_spaces,
  company_financing_status AS company_financing_status,
  business_status AS business_status,
  ownership_status AS ownership_status,
  universe AS universe,
  linkedin_url AS linkedin_url,
  SAFE_CAST(employees AS FLOAT64) AS employees,
  employee_history AS employee_history,
  exchange AS exchange,
  ticker AS ticker,
  parent_company AS parent_company,
  SAFE_CAST(last_updated_date AS TIMESTAMP) AS last_updated_date,
  SAFE_CAST(daily_updates AS FLOAT64) AS daily_updates,
  SAFE_CAST(weekly_updates AS FLOAT64) AS weekly_updates,
  primary_contact_pbid AS primary_contact_pbid,
  primary_contact AS primary_contact,
  primary_contact_title AS primary_contact_title,
  primary_contact_email AS primary_contact_email,
  primary_contact_phone AS primary_contact_phone,
  hq_location AS hq_location,
  hq_address_line_1 AS hq_address_line_1,
  hq_address_line_2 AS hq_address_line_2,
  hq_city AS hq_city,
  hq_state_province AS hq_state_province,
  hq_post_code AS hq_post_code,
  hq_country_territory_region AS hq_country_territory_region,
  hq_phone AS hq_phone,
  hq_fax AS hq_fax,
  hq_email AS hq_email,
  hq_global_region AS hq_global_region,
  hq_global_sub_region AS hq_global_sub_region,
  SAFE_CAST(first_financing_date AS TIMESTAMP) AS first_financing_date,
  SAFE_CAST(first_financing_size AS FLOAT64) AS first_financing_size,
  first_financing_size_status AS first_financing_size_status,
  SAFE_CAST(first_financing_valuation AS FLOAT64) AS first_financing_valuation,
  first_financing_valuation_status AS first_financing_valuation_status,
  first_financing_deal_type AS first_financing_deal_type,
  first_financing_deal_type_2 AS first_financing_deal_type_2,
  first_financing_deal_type_3 AS first_financing_deal_type_3,
  first_financing_deal_class AS first_financing_deal_class,
  first_financing_debt AS first_financing_debt,
  first_financing_status AS first_financing_status,
  SAFE_CAST(last_financing_date AS TIMESTAMP) AS last_financing_date,
  SAFE_CAST(last_financing_size AS FLOAT64) AS last_financing_size,
  last_financing_size_status AS last_financing_size_status,
  SAFE_CAST(last_financing_valuation AS FLOAT64) AS last_financing_valuation,
  last_financing_valuation_status AS last_financing_valuation_status,
  SAFE_CAST(last_valuation_step_up AS FLOAT64) AS last_valuation_step_up,
  last_financing_deal_type AS last_financing_deal_type,
  last_financing_deal_type_2 AS last_financing_deal_type_2,
  last_financing_deal_type_3 AS last_financing_deal_type_3,
  last_financing_deal_class AS last_financing_deal_class,
  SAFE_CAST(last_financing_debt_date AS TIMESTAMP) AS last_financing_debt_date,
  SAFE_CAST(last_financing_debt_size AS FLOAT64) AS last_financing_debt_size,
  last_financing_debt AS last_financing_debt,
  last_financing_status AS last_financing_status,
  general_services AS general_services,
  services_on_a_deal AS services_on_a_deal,
  SAFE_CAST(growth_rate AS FLOAT64) AS growth_rate,
  SAFE_CAST(growth_rate_percentile AS FLOAT64) AS growth_rate_percentile,
  SAFE_CAST(growth_rate_change AS FLOAT64) AS growth_rate_change,
  SAFE_CAST(growth_rate_change_1 AS FLOAT64) AS growth_rate_change_1,
  SAFE_CAST(web_growth_rate AS FLOAT64) AS web_growth_rate,
  SAFE_CAST(web_growth_rate_percentile AS FLOAT64) AS web_growth_rate_percentile,
  SAFE_CAST(similarweb_growth_rate AS FLOAT64) AS similarweb_growth_rate,
  SAFE_CAST(similarweb_growth_rate_percentile AS FLOAT64) AS similarweb_growth_rate_percentile,
  SAFE_CAST(majestic_growth_rate AS FLOAT64) AS majestic_growth_rate,
  SAFE_CAST(majestic_growth_rate_percentile AS FLOAT64) AS majestic_growth_rate_percentile,
  profile_data_source AS profile_data_source,
  SAFE_CAST(size_multiple AS FLOAT64) AS size_multiple,
  SAFE_CAST(size_multiple_percentile AS FLOAT64) AS size_multiple_percentile,
  SAFE_CAST(size_multiple_change AS FLOAT64) AS size_multiple_change,
  SAFE_CAST(size_multiple_change_1 AS FLOAT64) AS size_multiple_change_1,
  SAFE_CAST(web_size_multiple AS FLOAT64) AS web_size_multiple,
  SAFE_CAST(web_size_multiple_percentile AS FLOAT64) AS web_size_multiple_percentile,
  SAFE_CAST(similarweb_size_multiple AS FLOAT64) AS similarweb_size_multiple,
  SAFE_CAST(similarweb_size_multiple_percentile AS FLOAT64) AS similarweb_size_multiple_percentile,
  SAFE_CAST(majestic_size_multiple AS FLOAT64) AS majestic_size_multiple,
  SAFE_CAST(majestic_size_multiple_percentile AS FLOAT64) AS majestic_size_multiple_percentile,
  SAFE_CAST(similarweb_unique_visitors AS FLOAT64) AS similarweb_unique_visitors,
  SAFE_CAST(similarweb_unique_visitors_change AS FLOAT64) AS similarweb_unique_visitors_change,
  SAFE_CAST(similarweb_unique_visitors_change_1 AS FLOAT64) AS similarweb_unique_visitors_change_1,
  SAFE_CAST(majestic_referring_domains AS FLOAT64) AS majestic_referring_domains,
  SAFE_CAST(majestic_referring_domains_change AS FLOAT64) AS majestic_referring_domains_change,
  SAFE_CAST(majestic_referring_domains_change_1 AS FLOAT64) AS majestic_referring_domains_change_1,
  view_company_online AS view_company_online,
  ingested_at AS ingested_at
FROM `your-project-id.Pitchbook_raw.companies_raw`
WHERE company_id NOT LIKE "%© PitchBook Data, Inc.%"
QUALIFY ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY ingested_at DESC) = 1;
