-- View: Pitchbook.clean.investors_clean
-- Casts all numeric/timestamp/boolean fields from raw STRING ingestion,
-- strips PitchBook copyright footer rows, filters to active/relevant
-- investors (excludes non-VC types, inactive statuses, non-target regions),
-- and deduplicates by investor_id keeping the most recent ingestion.

SELECT
  investor_id AS investor_id,
  investors AS investors,
  SAFE_CAST(manual_download_date AS TIMESTAMP) AS manual_download_date,
  primary_investor_type AS primary_investor_type,
  SAFE_CAST(max_fund_size AS FLOAT64) AS max_fund_size,
  SAFE_CAST(aum AS FLOAT64) AS aum,
  SAFE_CAST(total_active_portfolio AS FLOAT64) AS total_active_portfolio,
  hq_location AS hq_location,
  website AS website,
  SAFE_CAST(number_of_investment_professionals AS FLOAT64) AS number_of_investment_professionals,
  primary_contact AS primary_contact,
  primary_contact_title AS primary_contact_title,
  primary_contact_email AS primary_contact_email,
  investor_legal_name AS investor_legal_name,
  SAFE_CAST(number_funds_open AS FLOAT64) AS number_funds_open,
  SAFE_CAST(number_funds_closed AS FLOAT64) AS number_funds_closed,
  SAFE_CAST(number_funds_closed_in_the_last_6_months AS FLOAT64) AS number_funds_closed_in_the_last_6_months,
  SAFE_CAST(number_funds_closed_in_the_last_12_months AS FLOAT64) AS number_funds_closed_in_the_last_12_months,
  SAFE_CAST(number_funds_closed_in_the_last_2_years AS FLOAT64) AS number_funds_closed_in_the_last_2_years,
  SAFE_CAST(number_funds_closed_in_the_last_5_years AS FLOAT64) AS number_funds_closed_in_the_last_5_years,
  SAFE_CAST(most_likely_fundraising AS BOOL) AS most_likely_fundraising,
  SAFE_CAST(min_fund_size AS FLOAT64) AS min_fund_size,
  SAFE_CAST(median_fund_size AS FLOAT64) AS median_fund_size,
  SAFE_CAST(total_funds_open AS FLOAT64) AS total_funds_open,
  SAFE_CAST(total_funds_closed AS FLOAT64) AS total_funds_closed,
  SAFE_CAST(total_funds_closed_in_the_last_6_months AS FLOAT64) AS total_funds_closed_in_the_last_6_months,
  SAFE_CAST(total_funds_closed_in_the_last_12_months AS FLOAT64) AS total_funds_closed_in_the_last_12_months,
  SAFE_CAST(total_funds_closed_in_the_last_2_years AS FLOAT64) AS total_funds_closed_in_the_last_2_years,
  SAFE_CAST(total_funds_closed_in_the_last_5_years AS FLOAT64) AS total_funds_closed_in_the_last_5_years,
  last_closed_fund_name AS last_closed_fund_name,
  SAFE_CAST(last_closed_fund_vintage AS FLOAT64) AS last_closed_fund_vintage,
  SAFE_CAST(last_closed_fund_size AS FLOAT64) AS last_closed_fund_size,
  last_closed_fund_type AS last_closed_fund_type,
  SAFE_CAST(last_closed_fund_close_date AS TIMESTAMP) AS last_closed_fund_close_date,
  SAFE_CAST(last_closed_fund_open_date AS TIMESTAMP) AS last_closed_fund_open_date,
  preferred_geography AS preferred_geography,
  preferred_verticals AS preferred_verticals,
  SAFE_CAST(preferred_investment_amount_max AS FLOAT64) AS preferred_investment_amount_max,
  SAFE_CAST(preferred_investment_amount_min AS FLOAT64) AS preferred_investment_amount_min,
  SAFE_CAST(preferred_investment_amount AS FLOAT64) AS preferred_investment_amount,
  SAFE_CAST(preferred_company_valuation_max AS FLOAT64) AS preferred_company_valuation_max,
  SAFE_CAST(preferred_company_valuation_min AS FLOAT64) AS preferred_company_valuation_min,
  SAFE_CAST(preferred_company_valuation AS FLOAT64) AS preferred_company_valuation,
  SAFE_CAST(preferred_deal_size_max AS FLOAT64) AS preferred_deal_size_max,
  SAFE_CAST(preferred_deal_size_min AS FLOAT64) AS preferred_deal_size_min,
  SAFE_CAST(preferred_deal_size AS FLOAT64) AS preferred_deal_size,
  SAFE_CAST(dry_powder AS FLOAT64) AS dry_powder,
  last_investment_company AS last_investment_company,
  SAFE_CAST(last_investment_date AS TIMESTAMP) AS last_investment_date,
  SAFE_CAST(last_investment_size AS FLOAT64) AS last_investment_size,
  last_investment_size_status AS last_investment_size_status,
  SAFE_CAST(last_investment_valuation AS FLOAT64) AS last_investment_valuation,
  last_investment_valuation_status AS last_investment_valuation_status,
  last_investment_type AS last_investment_type,
  last_investment_type_2 AS last_investment_type_2,
  last_investment_type_3 AS last_investment_type_3,
  last_investment_class AS last_investment_class,
  last_investment_debt AS last_investment_debt,
  SAFE_CAST(last_investment_debt_size AS FLOAT64) AS last_investment_debt_size,
  SAFE_CAST(last_investment_debt_date AS TIMESTAMP) AS last_investment_debt_date,
  last_investment_status AS last_investment_status,
  SAFE_CAST(total_exits AS FLOAT64) AS total_exits,
  SAFE_CAST(investments AS FLOAT64) AS investments,
  SAFE_CAST(investments_in_the_last_7_days AS FLOAT64) AS investments_in_the_last_7_days,
  SAFE_CAST(investments_in_the_last_6_months AS FLOAT64) AS investments_in_the_last_6_months,
  SAFE_CAST(investments_in_the_last_12_months AS FLOAT64) AS investments_in_the_last_12_months,
  SAFE_CAST(investments_in_the_last_2_years AS FLOAT64) AS investments_in_the_last_2_years,
  SAFE_CAST(investments_in_the_last_5_years AS FLOAT64) AS investments_in_the_last_5_years,
  hq_global_sub_region AS hq_global_sub_region,
  hq_global_region AS hq_global_region,
  hq_email AS hq_email,
  hq_state_province AS hq_state_province,
  hq_city AS hq_city,
  pbid AS pbid,
  SAFE_CAST(last_updated_date AS TIMESTAMP) AS last_updated_date,
  SAFE_CAST(total_investments AS FLOAT64) AS total_investments,
  SAFE_CAST(active_portfolio AS FLOAT64) AS active_portfolio,
  SAFE_CAST(year_founded AS FLOAT64) AS year_founded,
  SAFE_CAST(total_investments_in_the_last_7_days AS FLOAT64) AS total_investments_in_the_last_7_days,
  SAFE_CAST(total_investments_in_the_last_6_months AS FLOAT64) AS total_investments_in_the_last_6_months,
  SAFE_CAST(total_investments_in_the_last_12_months AS FLOAT64) AS total_investments_in_the_last_12_months,
  SAFE_CAST(total_investments_in_the_last_2_years AS FLOAT64) AS total_investments_in_the_last_2_years,
  SAFE_CAST(total_investments_in_the_last_5_years AS FLOAT64) AS total_investments_in_the_last_5_years,
  primary_contact_phone AS primary_contact_phone,
  primary_contact_pbid AS primary_contact_pbid,
  SAFE_CAST(exits AS FLOAT64) AS exits,
  investor_status AS investor_status,
  other_investor_types AS other_investor_types,
  description AS description,
  preferred_industry AS preferred_industry,
  preferred_investment_types AS preferred_investment_types,
  investor_also_known_as AS investor_also_known_as,
  investor_former_name AS investor_former_name,
  median_quartile AS median_quartile,
  SAFE_CAST(number_of_funds AS FLOAT64) AS number_of_funds,
  _1_top_quartile AS _1_top_quartile,
  _2_upper_mid_quartile AS _2_upper_mid_quartile,
  _3_lower_mid_quartile AS _3_lower_mid_quartile,
  _4_bottom_quartile AS _4_bottom_quartile,
  view_investor_online AS view_investor_online,
  ingested_at AS ingested_at
FROM `your-project-id.Pitchbook_raw.investors_raw`
WHERE
  investor_id NOT LIKE "%© PitchBook Data, Inc.%"
  AND hq_global_region NOT IN ("Africa", "Asia", "Oceania")
  AND investor_status NOT IN (
    "Acquired/Merged",
    "Acquired/Merged (Operating Subsidiary)",
    "Fully Invested, No Longer Seeking New Investments",
    "Not Making New Investments",
    "Out of Business"
  )
  AND primary_investor_type NOT IN (
    "Asset Manager",
    "Business Development Company",
    "Corporate Development",
    "Corporate Venture Capital",
    "Corporation",
    "Family Office",
    "Fund of Funds",
    "Fundless Sponsor",
    "Government",
    "Growth/Expansion",
    "Hedge Fund",
    "Holding Company",
    "Impact Investing",
    "Infrastructure",
    "Investment Bank",
    "Lender/Debt Provider",
    "Limited Partner",
    "Merchant Banking Firm",
    "Mezzanine",
    "Mutual Fund",
    "Not-For-Profit Venture Capital",
    "Other",
    "Other Private Equity",
    "PE-Backed Company",
    "PE/Buyout",
    "Real Estate",
    "Secondary Buyer",
    "Special Purpose Acquisition Company (SPAC)",
    "Sovereign Wealth Fund",
    "University",
    "VC-Backed Company"
  )
QUALIFY ROW_NUMBER() OVER (PARTITION BY investor_id ORDER BY ingested_at DESC) = 1;
